server:
  port: 8080
spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  # 소셜 로그인
##  security:
##    oauth2:
##      client:
##        registration:
##          github:
##            client-id: ${GITHUB_CLIENT_ID}
##            client-secret: ${GITHUB_CLIENT_SECRET}
##            scope:
##              - user:email # 사용자 이메일 접근 권한
##              - read:user # 사용자 정보 접근 권한
#aws:
#  s3:
#    bucketName: ${SB_NAME}
#    region: ${SB_REGION}
#    url: ${SB_URL}
#    accessKey: ${SB_AK}
#    secretKey: ${SB_SK}

